version: 2.1

orbs:
  node: circleci/node@11

jobs:
  build:
    test:
      executor:
        name: node/default
        tag: '11'

    steps:
      - checkout

      - node/install-packages

      - run:
          command: npm run test
      - run:
          name:
          command: |
            npm test -- --coverage

      - store_test_results:
          path: ./client/coverage/clover.xml

      - store_artifacts:
          path: ./client/coverage

workflows:
  test:
    jobs:
      - test
